resources:
- disallow-adding-capabilities.yaml
- restrict-sysctls.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/validationFailureAction
      value: enforce
  target:
    kind: ClusterPolicy
